package com.android.uz.infoapp.presentation.country_info;

import androidx.appcompat.app.AppCompatActivity;

import android.annotation.SuppressLint;
import android.content.Intent;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;

import com.android.uz.infoapp.presentation.category.CategoryActivity;
import com.android.uz.infoapp.presentation.main.MainActivity;
import com.android.uz.infoapp.R;
import com.android.uz.infoapp.presentation.start_quiz.StartQuizTest;
import com.android.uz.infoapp.data.model.CountryData;

import java.util.ArrayList;
import java.util.List;

public class CountryInfo extends AppCompatActivity {

    private List<CountryData> ls = new ArrayList<>();
    @SuppressLint("MissingInflatedId")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_country_info);

        loadData();
        findViewById(R.id.finishDescription).setOnClickListener(v -> finish());

        int getPos = getIntent().getIntExtra("POS", 0);
        CountryData countryData = ls.get(getPos);

        ImageView image = findViewById(R.id.infoFlag);
        TextView name = findViewById(R.id.infoName);
        TextView description = findViewById(R.id.infoText);

        image.setImageResource(countryData.getResId());
        name.setText(countryData.getName());
        description.setText(countryData.getDescreibtion());

        findViewById(R.id.homeButton).setOnClickListener(v -> {
            Intent intent = new Intent(CountryInfo.this, MainActivity.class);
            startActivity(intent);
            finish();

        });
        findViewById(R.id.quizButton).setOnClickListener(v -> {
            Intent intent = new Intent(CountryInfo.this, CategoryActivity.class);
            startActivity(intent);
            finish();
        });

    }
    private void loadData(){
        ls.add(new CountryData(R.drawable.hongkong, "Hong Kong", "Earliest known human traces in what is now Hong Kong are dated by some to 35,000 and 39,000 years ago during the Paleolithic period. The claim is based on an archaeological investigation in Wong Tei Tung, Sai Kung in 2003. The archaeological works revealed knapped stone tools from deposits that were dated using optical luminescence dating.[31]\n" +
                "\n" +
                "During the Middle Neolithic period, about 6,000 years ago, the region had been widely occupied by humans.[32] Neolithic to Bronze Age Hong Kong settlers were semi-coastal people. Early inhabitants are believed to be Austronesians in the Middle Neolithic period and later the Yueh people.[32] As hinted by the archaeological works in Sha Ha, Sai Kung, rice cultivation had been introduced since Late Neolithic period.[33] Bronze Age Hong Kong featured coarse pottery, hard pottery, quartz and stone jewelry, as well as small bronze implements.[32]\n" +
                "\n" +
                "The Qin dynasty incorporated the Hong Kong area into China for the first time in 214 BCE, after conquering the indigenous Baiyue.[34] The region was consolidated under the Nanyue kingdom (a predecessor state of Vietnam) after the Qin collapse[35] and recaptured by China after the Han conquest.[36] During the Mongol conquest of China in the 13th century, the Southern Song court was briefly located in modern-day Kowloon City (the Sung Wong Toi site) before its final defeat in the 1279 Battle of Yamen by the Yuan Dynasty.[37] By the end of the Yuan dynasty, seven large families had settled in the region and owned most of the land. Settlers from nearby provinces migrated to Kowloon throughout the Ming dynasty.[38]\n" +
                "\n" +
                "The earliest European visitor was Portuguese explorer Jorge Álvares, who arrived in 1513.[39][40] Portuguese merchants established a trading post called Tamão in Hong Kong waters and began regular trade with southern China. Although the traders were expelled after military clashes in the 1520s,[41] Portuguese-Chinese trade relations were re-established by 1549. Portugal acquired a permanent lease for Macau in 1557.[42]\n" +
                "\n" +
                "After the Qing conquest, maritime trade was banned under the Haijin policies. From 1661 to 1683, the population of most of the area forming present day Hong Kong was cleared under the Great Clearance, turning the region into a wasteland.[43] The Kangxi Emperor lifted the maritime trade prohibition, allowing foreigners to enter Chinese ports in 1684.[44] Qing authorities established the Canton System in 1757 to regulate trade more strictly, restricting non-Russian ships to the port of Canton.[45] Although European demand for Chinese commodities like tea, silk, and porcelain was high, Chinese interest in European manufactured goods was insignificant, so that Chinese goods could only be bought with precious metals. To reduce the trade imbalance, the British sold large amounts of Indian opium to China. Faced with a drug crisis, Qing officials pursued ever more aggressive actions to halt the opium trade.[46]"));
        ls.add(new CountryData(R.drawable.usa, "USA", "The United States of America (USA), commonly known as the United States (U.S.) or America, is a country primarily located in North America. It consists of 50 states, a federal district, five major unincorporated territories, and nine Minor Outlying Islands.[i] It includes 326 Indian reservations. The U.S. is the world's third-largest country by land and total area.[c] It shares land borders with Canada to its north and with Mexico to its south and has maritime borders with the Bahamas, Cuba, Russia, and other nations.[j] With a population of over 333 million,[k] it is the most populous country in the Americas and the third-most populous in the world. The national capital of the United States is Washington, D.C., and its most populous city and principal financial center is New York City.\n" +
                "\n" +
                "The first inhabitants of North America migrated across the Bering land bridge at least 12,000 years ago. Beginning in 1607, British colonization led to the establishment of the Thirteen Colonies in what is now the Eastern United States. They clashed with the British Crown over taxation and political representation, which led to the American Revolution and the ensuing Revolutionary War. The United States declared independence on July 4, 1776, becoming the first nation-state founded on Enlightenment principles of unalienable natural rights, consent of the governed, and republicanism. The country began expanding across North America, spanning the continent by 1848. Sectional division over slavery led to the secession of the Confederate States of America, which fought the remaining states of the Union during the American Civil War (1861–65). With the Union's victory and preservation, slavery was abolished nationally. Reforms, rapid economic development, and industrialization during the late 19th and early 20th centuries followed.\n" +
                "\n" +
                "By 1900, the United States had established itself as a great power, becoming the world's largest economy. After Japan's attack on Pearl Harbor in December 1941, the U.S. entered World War II on the side of the Allies.The aftermath of the war left the U.S. and the Soviet Union as the world's two superpowers and led to the Cold War, during which both countries engaged in a struggle for ideological dominance and international influence, avoided direct military conflict, and competed in the Space Race, which culminated with the United States landing the first humans on the Moon in 1969. Following the Soviet Union's collapse and the end of the Cold War in 1991, it emerged as the world's sole superpower. The 2020s saw the United States emerge as the leader of the AI spring, which has led to rapid and unprecedented development in artificial intelligence.\n" +
                "\n" +
                "The United States government is a federal presidential constitutional republic and liberal democracy with three separate branches of government: legislative, executive, and judicial. It has a bicameral national legislature composed of the House of Representatives, a lower house based on population; and the Senate, an upper house based on equal representation for each state. Many policy issues are decentralized at a state or local level, with widely differing laws by jurisdiction. Americans generally value liberty, individualism, and limited government. Culturally, the country is primarily Anglophonic, with other prominent regional influences."));
        ls.add(new CountryData(R.drawable.sudan, "Sudan", "Sudan (English: /suːˈdɑːn/ ⓘ soo-DAHN or /suːˈdæn/ soo-DAN; Arabic: السودان, romanized: Sūdān), officially the Republic of the Sudan (Arabic: جمهورية السودان, romanized: Jumhūriyyat as-Sūdān), is a country in Northeast Africa. It borders the Central African Republic to the southwest, Chad to the west, Egypt to the north, Eritrea to the northeast, Ethiopia to the southeast, Libya to the northwest, South Sudan to the south, and the Red Sea. It has a population of 45.7 million people as of 2022[21] and occupies 1,886,068 square kilometres (728,215 square miles), making it Africa's third-largest country by area and the third-largest by area in the Arab League. It was the largest country by area in Africa and the Arab League until the secession of South Sudan in 2011;[22] since then both titles have been held by Algeria. Its capital city is Khartoum, and its most populous city is Omdurman (part of the metropolitan area of Khartoum).\n" +
                "\n" +
                "History witnessed the Kingdom of Kerma (c. 2500–1500 BC), the Egyptian New Kingdom (c. 1500 BC–1070 BC), and the Kingdom of Kush (c. 785 BC–350 AD). After the fall of Kush, the Nubians formed the three Christian kingdoms of Nobatia, Makuria, and Alodia. Between the 14th and 15th centuries, most of Sudan was gradually settled by Arab nomads. From the 16th to the 19th centuries, central and eastern Sudan were dominated by the Funj sultanate, while Darfur ruled the west and the Ottomans the east. In 1811, Mamluks established a state at Dunqulah as a base for their slave trading. Under Turco-Egyptian rule of Sudan after the 1820s, the practice of trading slaves was entrenched along a north–south axis, with slave raids taking place in southern parts of the country and slaves being transported to Egypt and the Ottoman empire.[23] From the 19th century, the entirety of Sudan was conquered by the Egyptians under the Muhammad Ali dynasty. Religious-nationalist fervour erupted in the Mahdist Uprising in which Mahdist forces were eventually defeated by a joint Egyptian-British military force. In 1899, under British pressure, Egypt agreed to share sovereignty over Sudan with the United Kingdom as a condominium. In effect, Sudan was governed as a British possession.[24] The Egyptian revolution of 1952 toppled the monarchy and demanded the withdrawal of British forces from all of Egypt and Sudan. Muhammad Naguib, one of the two co-leaders of the revolution, and Egypt's first President, who was half-Sudanese and had been raised in Sudan, made securing Sudanese independence a priority of the revolutionary government. The following year, under Egyptian and Sudanese pressure, the United Kingdom agreed to Egypt's demand for both governments to terminate their shared sovereignty over Sudan and to grant Sudan independence. On 1 January 1956, Sudan was duly declared an independent state.\n" +
                "\n" +
                "After Sudan became independent, the Gaafar Nimeiry regime began Islamist rule.[25] This exacerbated the rift between the Islamic North, the seat of the government, and the Animists and Christians in the South. Differences in language, religion, and political power erupted in a civil war between government forces, influenced by the National Islamic Front (NIF), and the southern rebels, whose most influential faction was the Sudan People's Liberation Army (SPLA), which eventually led to the independence of South Sudan in 2011.[26] Between 1989 and 2019, a 30-year-long military dictatorship led by Omar al-Bashir ruled Sudan and committed widespread human rights abuses, including torture, persecution of minorities, alleged sponsorship global terrorism, and ethnic genocide in Darfur from 2003–2020. Overall, the regime killed an estimated 300,000 to 400,000 people. Protests erupted in 2018, demanding Bashir's resignation, which resulted in a coup d'état on 11 April 2019 and Bashir's imprisonment.[27]"));
        ls.add(new CountryData(R.drawable.yemen, "Yemen", "Yemen (/ˈjɛmən/ ⓘ; Arabic: ٱلْيَمَنْ, romanized: al-Yaman), officially the Republic of Yemen,[b] is a country in West Asia.[11] It is located in the southern end of the Arabian Peninsula, and borders Saudi Arabia to the north and Oman to the northeast. It shares maritime borders with Eritrea, Djibouti and Somalia. Covering 530,000 square kilometres (204,634 square miles) and having a coastline of approximately 2,000 kilometres (1,200 miles), Yemen is the second-largest Arab sovereign state on the Arabian Peninsula.[12] Sanaa is its constitutionally stated capital and largest city. The country's population is estimated to be 34.7 million as of 2023.[13] Yemen is a member of the Arab League, the United Nations, the Non-Aligned Movement and the Organisation of Islamic Cooperation.\n" +
                "\n" +
                "In ancient times, Yemen was the home of the Sabaeans,[14][15][16] a trading state that included parts of modern-day Ethiopia and Eritrea. Later in 275 AD, the Himyarite Kingdom was influenced by Judaism.[17] Christianity arrived in the fourth century, and Islam spread rapidly in the seventh century, with Yemenite troops playing a crucial role in early Islamic conquests.[18] Various dynasties emerged between the 9th and 16th centuries.[19] During the 1800s, the country was divided between the Ottoman and British empires. After World War I, the Mutawakkilite Kingdom of Yemen was established, which became the Yemen Arab Republic (North Yemen) in 1962 following a coup. South Yemen became independent in 1967. In 1990, the two Yemeni states united to form the modern Republic of Yemen (al-Jumhūrīyah al-Yamanīyah). President Ali Abdullah Saleh was the first president of the new republic until his resignation in 2012 in the wake of the Arab Spring.[20][21]\n" +
                "\n" +
                "Since 2011, Yemen has been facing a political crisis, marked by street protests against poverty, unemployment, corruption, and president Saleh's plan to amend Yemen's constitution and eliminate the presidential term limit.[22] Subsequently, the country has been engulfed in a civil war with multiple entities vying for governance, including the government of President Hadi (later the Presidential Leadership Council), the Houthi movement's Supreme Political Council, and the separatist Southern Movement's Southern Transitional Council. This ongoing conflict has led to a severe humanitarian crisis and received widespread criticism for its devastating impact on Yemen's people.[23][24][25][26][27]\n" +
                "\n" +
                "The ongoing humanitarian crisis and conflict has received widespread criticism for having a dramatic worsening effect on Yemen's humanitarian situation, that some say has reached the level of a \"humanitarian disaster\"[28] and some have even labelled it as a genocide.[29][30][31] Yemen is one of the least developed countries in the world,[32] facing significant obstacles to sustainable development[33] and is one of the poorest countries in the MENA region.[34] The United Nations reported in 2019 that Yemen had the highest number of people in need of humanitarian aid, amounting to about 24 million individuals, which is nearly 75% of its population.[35] As of 2020, Yemen ranked highest on the Fragile State Index[36] and second-worst on the Global Hunger Index, surpassed only by the Central African Republic.[36] Additionally, it has the lowest Human Development Index out of all non-African countries."));
        ls.add(new CountryData(R.drawable.china, "China", "China (Chinese: 中国; pinyin: Zhōngguó), officially the People's Republic of China (PRC),[k] is a country in East Asia. It is the world's second-most-populous country, with a population exceeding 1.4 billion. China spans the equivalent of five time zones and borders fourteen countries by land.[l] With an area of nearly 9.6 million square kilometers (3,700,000 sq mi), it is the third-largest country by total land area.[m] The country is divided into 22 provinces,[n] five autonomous regions, four municipalities, and two semi-autonomous special administrative regions. Beijing is the national capital, while Shanghai is the most populous city and largest financial center.\n" +
                "\n" +
                "The region has been inhabited since the Paleolithic era. The earliest Chinese dynastic states, such as the Shang and the Zhou, emerged in the basin of the Yellow River before the late second millennium BCE. The eighth to third centuries BCE saw a breakdown in Zhou authority and significant conflict, as well as the emergence of Classical Chinese literature and philosophy. In 221 BCE, China was unified under an emperor for the first time, ushering in more than two millennia in which China was governed by one or more imperial dynasties, including the Han, Tang, Ming, and Qing. Some of China's most notable achievements—such as the invention of gunpowder and paper, the establishment of the Silk Road, and the building of the Great Wall—occurred during this period. The imperial Chinese culture—including languages, traditions, architecture, philosophy and more—has heavily influenced East Asia.\n" +
                "\n" +
                "In 1912, the monarchy was overthrown and the Republic of China was established. The Republic saw consistent conflict for most of the mid-20th century, including a civil war between the Kuomintang government and the Chinese Communist Party (CCP), which began in 1927, as well as the Second Sino-Japanese War that began in 1937 and continued until 1945, therefore becoming involved in World War II. The latter led to a temporary stop in the civil war and numerous Japanese atrocities such as the Nanjing Massacre, which continue to influence China–Japan relations. In 1949, the CCP established control over China as the Kuomintang fled to Taiwan. Early communist rule saw two major projects: the Great Leap Forward, which resulted in a sharp economic decline and massive famine; and the Cultural Revolution, a movement to purge all non-communist elements of Chinese society that led to mass violence and persecution. Beginning in 1978, the Chinese government launched economic reforms that moved the country away from planned economics, but political reforms were cut short by the 1989 Tiananmen Square protests and massacre. Economic reform continued to strengthen the nation's economy in the following decades while raising China's standard of living significantly.\n" +
                "\n" +
                "China is a unitary one-party socialist republic led by the CCP. It is one of the five permanent members of the UN Security Council and a founding member of several multilateral and regional organizations such as the Asian Infrastructure Investment Bank, the Silk Road Fund, the New Development Bank, and the RCEP. It is a member of the BRICS, the G20, APEC, the SCO, and the East Asia Summit. China ranks poorly in measures of democracy, transparency, and human rights, including for press freedom, religious freedom, and ethnic equality. Making up around one-fifth of the world economy, China is the world's largest economy by GDP at purchasing power parity, the second-largest economy by nominal GDP, and the second-wealthiest country. The country is one of the fastest-growing major economies and is the world's largest manufacturer and exporter, as well as the second-largest importer, although its economic growth has slowed greatly in the 2020s. China is a nuclear-weapon state with the world's largest standing army by military personnel and the second-largest defense budget."));
        ls.add(new CountryData(R.drawable.vietnam, "Vietnam", "Vietnam[b] (Vietnamese: Việt Nam, [vîət nāːm] ⓘ), officially the Socialist Republic of Vietnam (SRV),[c] is a country at the eastern edge of mainland Southeast Asia, with an area of 331,700 square kilometres (128,100 sq mi) and a population of over 100 million, making it the world's fifteenth-most populous country. Vietnam shares land borders with China to the north, and Laos and Cambodia to the west. It shares maritime borders with Thailand through the Gulf of Thailand, and the Philippines, Indonesia, and Malaysia through the South China Sea. Its capital is Hanoi and its largest city is Ho Chi Minh City (commonly referred to by its former name, Saigon).\n" +
                "\n" +
                "Vietnam was inhabited by the Paleolithic age, with states established in the first millennium BC on the Red River Delta in modern-day northern Vietnam. The Han dynasty annexed Northern and Central Vietnam under Chinese rule from 111 BC, until the first dynasty emerged in 939. Successive monarchical dynasties absorbed Chinese influences through Confucianism and Buddhism, and expanded southward to the Mekong Delta, conquering Champa. During most of the 17th and 18th centuries, Vietnam was effectively divided into two domains of Đàng Trong and Đàng Ngoài. The Nguyễn—the last imperial dynasty—surrendered to France in 1883. In 1887, its territory was integrated into French Indochina as three separate regions. In the immediate aftermath of World War II, the nationalist coalition Viet Minh, led by the communist revolutionary Ho Chi Minh, launched the August Revolution and declared Vietnam's independence in 1945.\n" +
                "\n" +
                "Vietnam went through prolonged warfare in the 20th century. After World War II, France returned to reclaim colonial power in the First Indochina War, from which Vietnam emerged victorious in 1954. As a result of the treaties signed between the Viet Minh and France, Vietnam was also separated into two parts. The Vietnam War began shortly after, between the communist North, supported by the Soviet Union and China, and the anti-communist South, supported by the United States. Upon the North Vietnamese victory in 1975, Vietnam reunified as a unitary socialist state under the Communist Party of Vietnam (CPV) in 1976. An ineffective planned economy, a trade embargo by the West, and wars with Cambodia and China crippled the country further. In 1986, the CPV initiated economic and political reforms similar to the Chinese economic reform, transforming the country to a socialist-oriented market economy. The reforms facilitated Vietnamese reintegration into the global economy and politics.\n" +
                "\n" +
                "A developing country with a lower-middle-income economy, Vietnam is one of the fastest-growing economies of the 21st century. Vietnam has high levels of corruption, censorship, environmental issues and a poor human rights record; the country ranks among the lowest in international measurements of civil liberties, freedom of the press, and freedom of religion and ethnic minorities. It is part of international and intergovernmental institutions including the ASEAN, the APEC, the CPTPP, the Non-Aligned Movement, the OIF, and the WTO. It has assumed a seat on the United Nations Security Council twice.\n" +
                "\n"));
        ls.add(new CountryData(R.drawable.pakistan, "Pakistan", "Pakistan,[e] officially the Islamic Republic of Pakistan,[f] is a country in South Asia. It is the fifth-most populous country, with a population of over 241.5 million, having the largest Muslim population as of 2023.[8] Islamabad is the nation's capital, while Karachi is its largest city and financial centre. Pakistan is the 33rd-largest country by area, being the second largest in South Asia. Bounded by the Arabian Sea on the south, the Gulf of Oman on the southwest, and the Sir Creek on the southeast, it shares land borders with India to the east; Afghanistan to the west; Iran to the southwest; and China to the northeast. It shares a maritime border with Oman in the Gulf of Oman, and is separated from Tajikistan in the northwest by Afghanistan's narrow Wakhan Corridor.\n" +
                "\n" +
                "Pakistan is the site of several ancient cultures, including the 8,500-year-old Neolithic site of Mehrgarh in Balochistan,[13] the Indus Valley civilisation of the Bronze Age,[14][15] and the ancient Gandhara civilisation.[16] The regions that comprise the modern state of Pakistan were the realm of multiple empires and dynasties, including the Achaemenid, the Maurya, the Kushan, the Gupta;[17] the Umayyad Caliphate in its southern regions, the Samma, the Hindu Shahis, the Shah Miris, the Ghaznavids, the Delhi Sultanate, the Mughals,[18] and most recently, the British Raj from 1858 to 1947.\n" +
                "\n" +
                "Spurred by the Pakistan Movement, which sought a homeland for the Muslims of British India, and election victories in 1946 by the All-India Muslim League, Pakistan gained independence in 1947 after the Partition of the British Indian Empire, which awarded separate statehood to its Muslim-majority regions and was accompanied by an unparalleled mass migration and loss of life.[19] Initially a Dominion of the British Commonwealth, Pakistan officially drafted its constitution in 1956, and emerged as a declared Islamic republic. In 1971, the exclave of East Pakistan seceded as the new country of Bangladesh after a nine-month-long civil war. In the following four decades, Pakistan has been ruled by governments whose descriptions, although complex, commonly alternated between civilian and military, democratic and authoritarian, relatively secular and Islamist.[20] Pakistan elected a civilian government in 2008, and in 2010 adopted a parliamentary system with periodic elections.[21]\n" +
                "\n" +
                "Pakistan is a middle power nation,[22][23][24][25][26][27] and has the world's sixth-largest standing armed forces. It is a declared nuclear-weapons state, and is ranked amongst the emerging and growth-leading economies,[28] with a large and rapidly-growing middle class.[29] Pakistan's political history since independence has been characterised by periods of significant economic and military growth as well as those of political and economic instability. It is an ethnically and linguistically diverse country, with similarly diverse geography and wildlife. The country continues to face challenges, including poverty, illiteracy, corruption and terrorism.[30] Pakistan is a member of the United Nations, the Shanghai Cooperation Organisation, the Organisation of Islamic Cooperation, the Commonwealth of Nations, the South Asian Association for Regional Cooperation, and the Islamic Military Counter-Terrorism Coalition, and is designated as a major non-NATO ally by the United States."));
        ls.add(new CountryData(R.drawable.bahrein, "Bahrein", "Bahrain (/bɑːˈreɪn/ ⓘ bah-RAYN, /bæxˈreɪn/; Arabic: البحرين, romanized: al-Baḥrayn, locally [æl baħˈreːn] ⓘ), officially the Kingdom of Bahrain,[a] is an island country in West Asia. It is situated on the Persian Gulf, and comprises a small archipelago made up of 50 natural islands and an additional 33 artificial islands, centered on Bahrain Island which makes up around 83 per cent of the country's landmass. Bahrain is situated between Qatar and the northeastern coast of Saudi Arabia, to which it is connected by the King Fahd Causeway. The current population of Bahrain is 1,870,817 as of May 14, 2023, based on elaborations of the latest United Nations data, of whom 712,362 are Bahraini nationals.[2] Bahrain spans some 760 square kilometres (290 sq mi),[12] and is the third-smallest nation in Asia after the Maldives and Singapore.[13] The capital and largest city is Manama.\n" +
                "\n" +
                "Bahrain is the site of the ancient Dilmun civilization.[14] It has been famed since antiquity for its pearl fisheries, which were considered the best in the world into the 19th century.[15] Bahrain was one of the earliest areas to be influenced by Islam, during the lifetime of Muhammad in 628 AD. Following a period of Arab rule, Bahrain was ruled by the Portuguese Empire from 1521 until 1602, when they were expelled by Shah Abbas the Great of the Safavid Iran. In 1783, the Bani Utbah clan captured Bahrain from Nasr Al-Madhkur and it has since been ruled by the Al Khalifa royal family, with Ahmed al Fateh as Bahrain's first hakim.\n" +
                "\n" +
                "In the late 1800s, following successive treaties with the British, Bahrain became a protectorate of the United Kingdom.[16] In 1971, it declared independence. Formerly an emirate, Bahrain was declared an Islamic constitutional monarchy in 2002. In 2011, the country experienced protests inspired by the regional Arab Spring.[17] Bahrain's ruling Sunni Muslim Al Khalifa royal family has been criticised for violating the human rights of groups including dissidents, political opposition figures, and its majority Shia Muslim population.[18]\n" +
                "\n" +
                "Bahrain developed the first post-oil economy in the Persian Gulf,[19] the result of decades of investing in the banking and tourism sectors;[20] many of the world's largest financial institutions have a presence in the country's capital. It is recognised by the World Bank as a high-income economy. Bahrain is a member of the United Nations, Non-Aligned Movement, Arab League, Organisation of Islamic Cooperation and the Gulf Cooperation Council.[21] Bahrain is a Dialogue partner of the Shanghai Cooperation Organization."));
        ls.add(new CountryData(R.drawable.costarica, "Costa Rica", "Costa Rica (UK: /ˌkɒstə ˈriːkə/, US: /ˌkoʊstə-/ ⓘ; Spanish: [ˈkosta ˈrika]; literally \"Rich Coast\"), officially the Republic of Costa Rica (Spanish: República de Costa Rica), is a country in the Central American region of North America. Costa Rica is bordered by Nicaragua to the north, the Caribbean Sea to the northeast, Panama to the southeast, and the Pacific Ocean to the southwest, as well as maritime border with Ecuador to the south of Cocos Island. It has a population of around five million[10][11] in a land area of 51,060 km2 (19,710 sq mi). An estimated 333,980 people live in the capital and largest city, San José, with around two million people in the surrounding metropolitan area.[12]\n" +
                "\n" +
                "The sovereign state is a unitary presidential constitutional republic. It has a long-standing and stable democracy and a highly educated workforce.[13] The country spends roughly 6.9% of its budget (2016) on education, compared to a global average of 4.4%.[13] Its economy, once heavily dependent on agriculture, has diversified to include sectors such as finance, corporate services for foreign companies, pharmaceuticals, and ecotourism. Many foreign manufacturing and services companies operate in Costa Rica's Free Trade Zones (FTZ) where they benefit from investment and tax incentives.[14]\n" +
                "\n" +
                "Costa Rica was inhabited by indigenous peoples before coming under Spanish rule in the 16th century. It remained a peripheral colony of the empire until independence as part of the First Mexican Empire, followed by membership in the Federal Republic of Central America, from which it formally declared independence in 1847. Following the brief Costa Rican Civil War in 1948, it permanently abolished its army in 1949, becoming one of only a few sovereign nations without a standing army.[15][16][17]\n" +
                "\n" +
                "The country has consistently performed favorably in the Human Development Index (HDI), placing 58th in the world as of 2022, and fifth in Latin America.[18] It has also been cited by the United Nations Development Programme (UNDP) as having attained much higher human development than other countries at the same income levels, with a better record on human development and inequality than the median of the region.[19] It also performs well in comparisons of democratic governance, press freedom, subjective happiness and sustainable wellbeing. It has the 8th freest press according to the Press Freedom Index, it is the 35th most democratic country according to the Freedom in the World index and is the 23rd happiest country in the 2023 World Happiness Report"));
    }

}